apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: external-IP
deploy:
  # dont forget to export the kube context
  helm:
    releases:
    - name: ingress-nginx
      repo: https://kubernetes.github.io/ingress-nginx
      remoteChart: ingress-nginx
      version: 4.11.2
      setValues:
        controller:
          service:
            type: LoadBalancer
            externalTrafficPolicy: Local
          ingressClassResource:
            enabled: true
            name: nginx
      setValueTemplates:
        controller.service.externalIPs: 
          - "{{ .MAIN_NODE_IP }}"
        controller.ingressClassResource.controllerValue: "{{ .TOP_LEVEL_DOMAIN/ingress-nginx }}"
      namespace: default
      wait: true


---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: domain-tools
deploy:
  # dont forget to export the kube context
  helm:
    releases:
    - name: cert-manager
      repo: https://charts.jetstack.io
      remoteChart: cert-manager
      version: "v1.17.0"
      namespace: cert-manager
      createNamespace: true
      setValues:
        crds:
          enabled: true

    - name: cluster-issuer
      chartPath: manifests/helm/cert-issuer
      namespace: default
      setValues:
        enabled: true
      setValueTemplates:
        email: "{{ .ADMIN_EMAIL }}"
      dependsOn: ["cert-manager"]


--- 
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: kubernetes-dashboard
deploy:
  # dont forget to export the kube context
  helm:
    releases:
    - name: kubernetes-dashboard
      repo: https://kubernetes.github.io/dashboard
      remoteChart: kubernetes-dashboard  
      version: 7.13.0
      namespace: tools
      createNamespace: true
      setValues:
        app:
          ingress:
            enabled: true
            ingressClassName: nginx
            issuer:
              name: letsencrypt-prod
              scope: cluster
            tls:
              enabled: true
              secretName: kubernetes-dashboard-tls
      setValueTemplates:
        app.ingress.hosts:
          - "{{ printf \"cluster.%s\" .TOP_LEVEL_DOMAIN }}"


---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: plausible-analytics
deploy:
  helm:
    releases:
    - name: plausible-analytics
      chartPath: manifests/helm/plausible-analytics
      namespace: tools
      createNamespace: true
      setValues:     
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
      setValueTemplates:
        tls:
          hosts:
          - plausible.{{ .TOP_LEVEL_DOMAIN }}
          secretName: plausible-analytics-tls
        postgresql.auth.password: "{{ .PLAUSIBLE_PASSWORD }}"
        databaseURL: "postgresql://plausible:{{ .PLAUSIBLE_PASSWORD }}@plausible-analytics-postgresql.tools.svc.cluster.local:5432/plausible"
        clickhouse.auth.password: "{{ .PLAUSIBLE_CLICKHOUSE_PASSWORD }}"
        clickhouseURL: "http://clickhouse:{{ .PLAUSIBLE_PASSWORD }}@plausible-analytics-clickhouse.tools.svc.cluster.local:8123/plausible_events_db"



       