annotations:
  cert-manager.io/cluster-issuer: letsencrypt-prod
 
tls:
  - hosts:
    - examples-new.hololinked.dev
    - external-examples-new.hololinked.dev
    secretName: examples-new-hololinked-dev-tls

rules:
- host: examples-new.hololinked.dev
  http:
    paths:
      - path: /simulations/oscilloscope
        pathType: Prefix
        backend:
          service:
            name: oscilloscope-simulator
            port:
              number: 80
      - path: /simulations/spectrometer
        pathType: Prefix
        backend:
          service:
            name: spectrometer-simulator
            port:
              number: 80

- host: external-examples-new.hololinked.dev
  http:
    paths:
      - path: /advanced-coffee-machine
        pathType: Prefix
        backend:
          service:
            name: node-wot-advanced-coffee-machine-simulator
            port:
              number: 80
      - path: /data-schema-thing 
        pathType: Prefix
        backend:
          service:
            name: node-wot-http-data-schema-thing-simulator
            port:
              number: 80