annotations:
  cert-manager.io/cluster-issuer: letsencrypt-prod
 
tls:
  - hosts:
    - hololinked.dev
    secretName: hololinked-dev-tls

rules:
- host: hololinked.dev
  http:
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
