annotations:
  cert-manager.io/cluster-issuer: letsencrypt-prod
 
tls:
  - hosts:
    - control-panel.hololinked.dev
    secretName: control-panel-hololinked-tls

rules:
- host: control-panel.hololinked.dev
  http:
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: control-panel
            port:
              number: 80
- host: no-ssl.control-panel.hololinked.net
  http:
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: control-panel
            port:
              number: 80
