{{- if .Values.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Values.environment }}
spec:
  acme:
    server: {{ include "cert-issuer.acmeServer" . }}
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ include "cert-issuer.fullname" . }}-key
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.ingressClassName }}
{{- end }}